version: '3'
services:
  #  hackiebox-transparent:
  #    container_name: hackiebox-transparent
  #    hostname: hackiebox-transparent
  #    image: hbs:latest
  #    environment:
  #      #- SSLKEYLOGFILE=/root/sslkeylogfile.txt
  #      - MITMPROXY_MODE=transparent
  #      #- NET_IF=eth1
  #      - ROOT_PASS=root #For SSH access (and tcpdump)
  #      #- TONIEBOX_FIXED_CERT=toniebox-v1.pem
  #      #- TONIEBOX_FALLBACK_CERT=toniebox-v1.pem
  #    tty: true
  #    privileged: true
  #    ports:
  #      - 8022:8022
  #      - 8080:8080
  #      - 8081:8081
  #    volumes:
  #      - certs:/root/.mitmproxy
  #      - content:/root/CONTENT
  #      - client-certs:/root/client-certs
  #      - config:/root/config
  #      - ssh:/etc/ssh
  #    networks:
  #      lan: 
  #        ipv4_address: <IP-T-LAN>
  #      mitm: 
  #        ipv4_address: <IP-T-MITM>
  #    restart: unless-stopped
  hackiebox-reverse:
    container_name: hackiebox-reverse
    hostname: hackiebox-reverse
    image: hbs:latest
    dns:
      - 1.1.1.1
      - 8.8.8.8
    environment:
      #- SSLKEYLOGFILE=/root/sslkeylogfile.txt
      - MITMPROXY_MODE=reverse 
      - TONIEBOX_URL_PROD=prod.revvox #custom local dns name for prod server (reverse proxy)
      - TONIEBOX_URL_RTNL=rtnl.revvox #custom local dns name for rtnl server (reverse proxy)
      - ROOT_PASS=root #For SSH access (and tcpdump)
      #- TONIEBOX1_IP_MAC = 192.168.1.2/00:00:00:00:00:00 # link mac to ip if you are NOT running in host mode
      #- TONIEBOX2_IP_MAC = 192.168.1.2/00:00:00:00:00:00
      #- TONIEBOX3_IP_MAC = 192.168.1.2/00:00:00:00:00:00
      #- TONIEBOX_FIXED_CERT=toniebox-v3.pem
      #- TONIEBOX_FALLBACK_CERT=toniebox-v3.pem
    tty: true
    ports:
      - 443:443
      - 8081:8081
    volumes:
      - ./mitmproxy-cert:/root/.mitmproxy
      - ./content:/root/CONTENT
      - ./client-cert:/root/client-certs
      - ./config:/root/config
      - ./ssh:/etc/ssh
    restart: unless-stopped
