version: '3'
services:
  mitmweb:
    container_name: mitmproxy-toniebox
    hostname: mitmproxy-toniebox
    image: <TO-BE-FILLED>
    environment:
      - NET_IF=eth2
      - TONIEBOX_CHIP=cc3200 #cc3200/cc32xx
      - ROOT_PASS=root #For SSH access (and tcpdump)
      #- TONIEBOX_CLIENT_CERT="" #Use a fixed cert from the client_certs dir instead of autoselecting it
    tty: true
    privileged: true
    ports:
      - 8022:8022
      - 80:80
      - 443:443
      - 8080:8080
      - 8081:8081
    command: mitmweb --web-host 0.0.0.0 --mode transparent --ssl-insecure -s /home/mitmproxy/addons/TonieboxAddonStart.py
    volumes:
      - certs:/home/mitmproxy/.mitmproxy
      - content:/home/mitmproxy/CONTENT
      - client-certs:/home/mitmproxy/client-certs
      - config:/home/mitmproxy/config
      - ssh:/etc/ssh
    network_mode: host
    restart: unless-stopped
volumes:
  certs:
  content:
  client-certs:
  config:
  ssh: