# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: toniebox.pb.rtnl.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16toniebox.pb.rtnl.proto\"o\n\rTonieRtnlLog2\x12\x0e\n\x06\x66ield1\x18\x01 \x02(\x06\x12\x0e\n\x06\x66ield2\x18\x02 \x02(\r\x12\x0e\n\x06\x66ield3\x18\x03 \x02(\r\x12\x0e\n\x06\x66ield4\x18\x04 \x02(\r\x12\x0e\n\x06\x66ield5\x18\x05 \x02(\r\x12\x0e\n\x06\x66ield6\x18\x06 \x02(\x0c\"/\n\rTonieRtnlLog3\x12\x0e\n\x06\x66ield1\x18\x01 \x02(\x07\x12\x0e\n\x06\x66ield2\x18\x02 \x02(\r')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'toniebox.pb.rtnl_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TONIERTNLLOG2._serialized_start=26
  _TONIERTNLLOG2._serialized_end=137
  _TONIERTNLLOG3._serialized_start=139
  _TONIERTNLLOG3._serialized_end=186
# @@protoc_insertion_point(module_scope)
