name: Docker Image CI

on:
  workflow_dispatch:
  push:
    tags:
      - hbs_nightly
      - hbs_v*
#    branches: [ "master" ]
#  pull_request:
#    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag revvox/hackiebox-server:$(date +%s) --tag revvox/hackiebox-server:latest
